#!/bin/sh

[ -f /etc/dnsmasq.conf ] || exit 0

case "$1" in
	start)
		printf "Starting dnsmasq: "
		ip link add name br-lan type bridge
		ip link set br-lan up
		if ifconfig -a | grep eth0 > /dev/null; then
			ifconfig eth0 up
			ip link set dev eth0 master br-lan
		fi
		if ifconfig -a | grep usb0 > /dev/null; then
			ifconfig usb0 up
			ip link set dev usb0 master br-lan
		fi
		ifconfig br-lan 192.168.34.1 up
		start-stop-daemon -S -x /usr/sbin/dnsmasq
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)
		printf "Stopping dnsmasq: "
		ip link delete br-lan
		start-stop-daemon -K -q -x /usr/sbin/dnsmasq
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	restart|reload)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit 0
